
service: ssr

provider:
  name: aws
  runtime: nodejs12.x


functions:
  app:
    handler: handler.ssr
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
